demo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'  # Ensure this matches the exact name of the ODBC driver
      server: poojaserver.database.windows.net # Use the fully qualified domain name for Azure SQL Server
      port: 1433
      database: poojadatabase
      schema: dbo
      windows_login: False
      trust_cert: True
      user: poojaadmin
      password: $Pooja@123
